#!/usr/bin/env node
/* eslint-disable no-console, angular/log */

const JestExRunner = require('jest-ex').JestExRunner;
const chalk = require('chalk');

new JestExRunner('./.jest.json', {
    addTransformer: true,
    addStubs: true,
    cache: false,
})
.run()
.then(() => chalk.green('Yay! all the unit tests passed!'))
.catch(() => chalk.red('Damn... something went wrong with the unit tests'));
